### ISSUE TITLE
Move repository to Jaxboards org

### ISSUE THREAD

**Issue by DevopsIce** [seanjohnson08/JXBD_Git#6]
Suggest consolidating the software around JXBD under a single org.

I've created https://github.com/Jaxboards/ on which @seanjohnson08 and @wtl420 both act as owners. If this is agreed on, both can manually accept the moving request after it comes from @seanjohnson08's account.

I believe this will positively impact visibility for the project as well as its community and author(s).

**Comment by seanjohnson08** [comment]
Great suggestion @DevopsIce - I think what will end up happening is that the Jaxboards/Jaxboards repo will supercede this one. It's already lightyears ahead of this repo.
